### PR TITLE
Implementing new methods 

### PR DESCRIPTION
**Pull request by ElySeraidarian**
This PR aims to solve #23, everything should be working.

### CODE REVIEW

**Comment by RiboRings** [comment]
Thank you for the PR!

What does .cacheCommonInfo do? Is it something essential, or can we avoid using it?

**Comment by ElySeraidarian** [comment]
It is supposed to keep in cache data that we would need through our panels so that we don't have to compute them each time (for example we could use .getCachedCommonInfo to get colData information instead of calling colData function for each field in inputs). I'd have to replace these in order to be useful, otherwise it's pretty useless. (also if functions are called only once shouldn't be useful)

**Comment by RiboRings** [comment]
Ok nice!

Do you see any place that we are using a function multiple times and it would be beneficial to use .getCachedCommonInfo instead?

We should aim for minimal code, so if it is not strictly necessary we can avoid using this extra method.

**Comment by ElySeraidarian** [comment]
Not really, maybe in RowTreePlot ? Anyways I don't think this is really useful but maybe in the future it can be?

**Comment by RiboRings** [comment]
Then we can skip it. How about .refineParameters?

**Comment by ElySeraidarian** [comment]
This is linked to .cacheCommonInfo method (they go together), this is to be sure data is well loaded, especially for slots we are using in inputs ( making sure there is no NA value or invalid value). If we remove .cacheCommonInfo, we can also remove this one also as it uses the cache data (and I don't think it is really useful too as it was perfectly working before)

**Comment by RiboRings** [comment]
Ok thanks for digging in those methods!

Then we can remove those and just keep .exportOutput. It would be great if we can add tests for .exportOutput for the different panels.

**Comment by ElySeraidarian** [comment]
Made changes, not really familiar with tests but I tried my best with what already existed & iSEE tests

**Review by RiboRings — APPROVED** [review]

**Pull request merged**
